#!/bin/sh

# 自定义版本号
#sed -i "/DISTRIB_REVISION/s/\'/ REVISION_tobeupdated\'/2"  /etc/openwrt_release
sed -i "/DISTRIB_DESCRIPTION/s/\'/ DESCRIPTION_tobeupdated\'/2" /etc/openwrt_release

# 设置shellclash
echo "alias clash=\"sh /etc/clash/clash.sh\"" >> /etc/profile
echo "export clashdir=\"/etc/clash\"" >> /etc/profile
#chmod 755 /etc/clash/init.sh
#cd /etc/clash/ && /etc/clash/init.sh
cp -f /etc/clash/clashservice /etc/init.d/clash
chmod 755 /etc/init.d/clash
/etc/init.d/clash enable

chmod +x /etc/tinc/tincvpn/tinc-up
chmod +x /etc/tinc/tincvpn/tinc-down
chmod 400 /etc/dropbear/authorized_keys
chmod 644 /etc/dropbear

exit 0
