#!/bin/sh

uci set luci.main.lang=zh_cn
uci commit luci

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

sed -i "s|DISTRIB_REVISION='|DISTRIB_REVISION='REVISION_tobeupdated|g"  /etc/openwrt_release

exit 0
