name: test

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
        

   
    - name: Download files
      working-directory: ${{ github.workspace }}/runner_root/
      run: |
        wget -q --no-check-certificate -O /tmp/test.tar.gz https://zoenix.cc/xyz/github//test.tar.gz  && tar -xzf /tmp/test.tar.gz

    - name: Upload
      uses: thinkcyy/Action_OpenWrt_composite@release
      
    - name: Create release
      uses: ncipollo/release-action@main
      with:
        name: ${{ env.TAG_NAME }}
        allowUpdates: true
        tag: ${{ env.TAG_NAME }}
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ./runner_root/artifact/*
