name: ImageBuilder_ImmortalWrt-EA8500

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:   

    - name: Initialization
      uses: thinkcyy/Action_Initialization@main
      
#    - name: Clone files
#      uses: actions/checkout@main
#      with:
#         repository: thinkcyy/openwrt-config
#         ref: 'test1'
#         token: ${{ secrets.THINKCYY_TOKEN }}
#         path: ./openwrt-config   
             
    - name: Compile
      uses: thinkcyy/Action_LeanWRT_composite@OpenWrt
      with:
           ROUTER_MODEL: EA8500
           REPO_TYPE: ImmortalWrt
           IMAGEBUILDER: y
           #FILES_CONFIG: test           
           COMPILE_CONFIG: EA8500-20240607-2-dawn
           OP_REPO: immortalwrt/immortalwrt
           REPO_BRANCH: v23.05.2
           REPO_DEPTH: 1           
           #REPO_COMMIT: 32e4c50d24d08570c6ae34d05922f1d9d879c0f2
           
