name: ImageBuilder_zhKong-AX6

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        
    - name: Initialization
      uses: thinkcyy/Action_Initialization@main                
                   
    - name: Compile
      uses: thinkcyy/Action_OpenWrt_composite@zhKong
      with:
           ROUTER_MODEL: AX6
           COMPILE_CONFIG: AX6-ImageBuilder-20240625-thinkcy-setttings
           REPO_TYPE: zhKong
           IMAGEBUILDER: y                                 
           OP_REPO: thinkcyy/AX3600-OpenWrt
           REPO_BRANCH: main_nss
           #REPO_COMMIT: 
           
    - name: Create release
      id: create_release
      uses: ncipollo/release-action@main
      with:
        name: OpenWrt-${{ env.TAG_NAME }}
        allowUpdates: true
        tag: ${{ env.TAG_NAME }}
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ./OpenWRT-Action/artifact/* 
