name: test

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
        
    #- name: Initialization
    #  uses: thinkcyy/Action_Initialization@fast
                   
    - name: compile
      uses: thinkcyy/Action_OpenWrt_composite@compile
      with:           
           RELEASE_PREFIX: "[Cron]"
           COMPILE_CONFIG_BASE: Qosmio-qualcommax_ipq807x
           COMPILE_CONFIG_DIFF: "common.cust.package-1-OpenWrt_Component common.cust.package-2-luci_app common.cust.package-3-netfilter"
           #COMPILE_CONFIG_AUTOMERGE: common.cust.package
           COMPILE_CONFIG: common.cust.package-4-nss
           CONFIG_TO_DEL: "CONFIG_PACKAGE_kmod-nft-netdev CONFIG_PACKAGE_kmod-macvlan"           
           IMAGEBUILDER: y
           REPO_TYPE: Qosmio
           OP_REPO: qosmio/openwrt-ipq
           REPO_BRANCH: main-nss
           CUSTOM_FEEDS_SH: custom_feeds-Qosmio
           token: ${{ secrets.GITHUB_TOKEN }} 
