name: ImageBuilder_zhKong-AX6_main_nss

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        
    - name: Initialization
      uses: thinkcyy/Action_Initialization@quick                
                   
    - name: Prepare
      uses: thinkcyy/Action_OpenWrt_composite@prepare_v2
      with:
           ROUTER_MODEL: AX6
           COMPILE_CONFIG: AX6-20240707-minimal
           IMAGEBUILDER: y
           REPO_TYPE: zhKong
           OP_REPO: AgustinLorenzo/openwrt
           REPO_BRANCH: main_nss
           REPO_DATE: '2024-07-05T23:59:59+08:00'
           #REPO_DATE: ad3b782
           #DEFAULT_FEEDS:  feeds.conf.default-main_nss_wifi
           #EXTRA_FEEDS: add_feeds_cus_lean
           #CUSTOM_FEEDS_SH: custom_feeds-202403
           #如果DEFAULT_FEEDS已自带HASH，MATCH_FEED_HASH要取消设定
           #MATCH_FEED_HASH: y
           #ACTION_DATE: fc19ca2
           #ACTION_DATE: '2024-07-03T23:59:59+08:00'
           #FEEDS_DATE:  '2024-06-15T23:59:59+08:00'
           
    - name: Download package sources
      working-directory: ${{ github.workspace }}/runner_root/openwrt
      run: make download V=s

    - name: Build tools
      working-directory: ${{ github.workspace }}/runner_root/openwrt
      run: |
        make tools/install -j$(nproc) V=s || \
        make tools/install V=s
        
    - name: Build toolchain
      working-directory: ${{ github.workspace }}/runner_root/openwrt
      run: |
        make toolchain/install -j$(nproc) V=s || \
        make toolchain/install V=s

    - name: Build target images
      working-directory: ${{ github.workspace }}/runner_root/openwrt
      run: |
        make -j$(nproc) V=s || \
        make V=s

    - name: Upload
      uses: thinkcyy/Action_OpenWrt_composite@release
      
    - name: Create release
      uses: ncipollo/release-action@main
      with:
        name: OpenWrt-zhKong-main_nss-${{ env.TAG_NAME }}
        allowUpdates: true
        tag: ${{ env.TAG_NAME }}
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ./runner_root/artifact/*
