name: zhKong-ACwifidude-24.10-test

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
        
    - name: Initialization
      uses: thinkcyy/Action_Initialization@main               
                   
    - name: repo
      working-directory: ${{ github.workspace }}/runner_root
      run: |
        git clone -b openwrt-23.05-nss-qsdk11 https://github.com/ACwifidude/openwrt.git openwrt
        cd openwrt
        git remote add upstream https://git.openwrt.org/openwrt/openwrt.git
        git fetch upstream && git rebase upstream/openwrt-24.10
        ./scripts/feeds update -a && ./scripts/feeds install -a && cp diffconfig .config && make defconfig && ./scripts/getver.sh
           
    - name: Replace IB
      working-directory: ${{ github.workspace }}/runner_root
      run: |
        cp -r imagebuilder ./openwrt/target/
           
    - name: Download package sources
      working-directory: ${{ github.workspace }}/runner_root/openwrt
      run: make download V=s

    - name: Build tools
      working-directory: ${{ github.workspace }}/runner_root/openwrt
      run: |
        make tools/install -j$(nproc) V=s || \
        make tools/install V=s
        
    - name: Build toolchain
      working-directory: ${{ github.workspace }}/runner_root/openwrt
      run: |
        make toolchain/install -j$(nproc) V=s || \
        make toolchain/install V=s

    - name: Build target images
      working-directory: ${{ github.workspace }}/runner_root/openwrt
      run: |
        make -j$(nproc) V=s || \
        make V=s

    - name: Upload
      uses: thinkcyy/Action_OpenWrt_composite@release
      
    - name: Create release
      uses: ncipollo/release-action@main
      with:
        name: ${{ env.TAG_NAME }}
        allowUpdates: true
        tag: ${{ env.TAG_NAME }}
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ./runner_root/artifact/*
