name: Qosmio-cron

on:
   workflow_dispatch:
   schedule:
    - cron: '0 20 * * *'

jobs:
  check:
    outputs:
      status: ${{ steps.early.conclusion }}
    runs-on: ubuntu-22.04
    steps:
      
    - id: early
      name: Early exit
      env:
        OP_REPO: qosmio/openwrt-ipq
        REPO_BRANCH: main-nss                 
      run: |
        echo 下载源仓库
        git clone https://github.com/${{ OP_REPO }} $([[ ${{ REPO_BRANCH }} != 'n' ]] && echo "-b ${{ REPO_BRANCH }} --single-branch")  ./openwrt
        echo 获取最新提交日期
        LAST=$(git log -1 --format="%cd" --date=format:"%Y-%m-%d %H:%M:%S")
        echo 最新提交日期为$LAST
        echo 判断是否24小时内更新
        [[ `expr $(($(date +%s) - $(date +%s -d "$LAST")))` -lt 86400 ]] && (echo 24小时内有更新，继续 ; exit 0 ) || (echo 24小时内无更新，退出 ; exit 1 )      
      
  build:
    needs: check
    if: needs.check.outputs.status == 'success'
    runs-on: ubuntu-22.04
    steps:
        
    - name: Initialization
      uses: thinkcyy/Action_Initialization@main
                   
    - name: Prepare
      uses: thinkcyy/Action_OpenWrt_composite@prepare
      with:           
           REPO_BRANCH: main-nss
           COMPILE_CONFIG_BASE: Qosmio-qualcommax_ipq807x
           COMPILE_CONFIG_DIFF: "common.cust.package-1-OpenWrt_Component common.cust.package-2-luci_app common.cust.package-3-netfilter"
           #COMPILE_CONFIG_AUTOMERGE: common.cust.package
           COMPILE_CONFIG: common.cust.package-4-nss
           IMAGEBUILDER: y
           CUSTOM_FEEDS_SH: custom_feeds-Qosmio
           REPO_TYPE: Qosmio
           OP_REPO: qosmio/openwrt-ipq

    - name: Modify config
      uses: thinkcyy/Action_OpenWrt_composite@config_add
      with:
           # CONFIG_TO_ADD: ' '
           CONFIG_TO_DEL: "CONFIG_PACKAGE_kmod-nft-netdev CONFIG_PACKAGE_kmod-macvlan"
                      
    - name: Download package sources
      working-directory: ${{ github.workspace }}/runner_root/openwrt
      run: make download V=s

    - name: Build tools
      working-directory: ${{ github.workspace }}/runner_root/openwrt
      run: |
        make tools/install -j$(nproc) V=s || \
        make tools/install V=s
        
    - name: Build toolchain
      working-directory: ${{ github.workspace }}/runner_root/openwrt
      run: |
        make toolchain/install -j$(nproc) V=s || \
        make toolchain/install V=s

    - name: Build target images
      working-directory: ${{ github.workspace }}/runner_root/openwrt
      run: |
       make -i -j$(nproc) V=s || make -i V=s
       # make -j$(nproc) V=s || make V=s

    - name: Upload
      uses: thinkcyy/Action_OpenWrt_composite@release
      
    - name: Create release
      uses: ncipollo/release-action@main
      with:
        name: ${{ env.TAG_NAME }}
        allowUpdates: true
        tag: ${{ env.TAG_NAME }}
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ./runner_root/artifact/*
