name: Reuse_Action_zhKong-AX6

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Show system
      run: |
        echo -e "Total CPU cores\t: $(nproc)"
        cat /proc/cpuinfo | grep 'model name'
        ulimit -a
        echo "ROUTER_MODEL=AX6" >> $GITHUB_ENV
        echo "FILES_CONFIG=public" >> $GITHUB_ENV
        echo "COMPILE_CONFIG=AX6-20240325-avahi" >> $GITHUB_ENV    

    - name: Compile
      uses: thinkcyy/Action_zhKong_1-checkout-and-config@main
      with:
           ROUTER_MODEL: AX6
           COMPILE_CONFIG: AX6-20240325-avahi            
          
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: OpenWrt-${{ inputs.COMPILE_CONFIG }}-${{ env.tag_name }}
        path: /home/runner/work/OpenWRT-Action/OpenWRT-Action/OpenWRT-Action/artifact/
