name: Reuse_Action_zhKong-AX6-V2

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Show system
      run: |
        echo "ROUTER_MODEL=AX6" >> $GITHUB_ENV
        echo "FILES_CONFIG=public" >> $GITHUB_ENV
        echo "COMPILE_CONFIG=AX6-20240429-remove-privoxy" >> $GITHUB_ENV  
        
    - name: Compile
      uses: thinkcyy/Action_zhKong_composite@test
      with:
           ROUTER_MODEL: ${{ env.ROUTER_MODEL }}
           COMPILE_CONFIG: ${{ env.COMPILE_CONFIG }}            
          
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: OpenWrt-${{ env.COMPILE_CONFIG }}-${{ env.FILES_CONFIG }}-${{ env.tag_name }}
        path: /home/runner/work/OpenWRT-Action/OpenWRT-Action/OpenWRT-Action/artifact/
