name: Reuse_Action_LeanWRT-EA8500-test

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:   

    - name: Initialization
      uses: thinkcyy/Action_Initialization@main
      
    - name: Clone files
      uses: actions/checkout@main
      with:
         repository: thinkcyy/openwrt-config
         ref: 'test1'
         token: ${{ secrets.THINKCYY_TOKEN }}
         path: ./openwrt-config   
             
    - name: Compile
      uses: thinkcyy/Action_LeanWRT_composite@main
      with:
           ROUTER_MODEL: EA8500
           FILES_CONFIG: test
           COMPILE_CONFIG: EA8500-20240524-full-NSS-without-crypto
           OP_REPO: coolsnowwolf/lede
           #REPO_DEPTH: 1
           #ipq806x: 5.10内核编译失败，退回至切换至前一天2024.1.23版本
           REPO_COMMIT: a5823d43b1765fdf0d8e2eed18e0e47d58e6301b
           
    - name: Create release
      id: create_release
      uses: ncipollo/release-action@v1.12.0
      with:
        name: LeanWrt-${{ env.TAG_NAME }}
        allowUpdates: true
        tag: ${{ env.TAG_NAME }}
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ./OpenWRT-Action/artifact/*      
