name: Reuse_Action_LeanWRT-EA8500

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Show system
      run: |
        echo "ROUTER_MODEL=EA8500" >> $GITHUB_ENV
        echo "FILES_CONFIG=public" >> $GITHUB_ENV
        echo "COMPILE_CONFIG=20240424-remove-igmpproxy" >> $GITHUB_ENV     
        
    - name: Compile
      uses: thinkcyy/Action_LeanWRT_composite@main
      with:
           ROUTER_MODEL: ${{ env.ROUTER_MODEL }}
           COMPILE_CONFIG: ${{ env.COMPILE_CONFIG }}    
           
    - name: Create release
      id: create_release
      uses: ncipollo/release-action@v1.12.0
      with:
        name: OpenWrt-${{ env.TAG_NAME }}
        allowUpdates: true
        tag: ${{ env.TAG_NAME }}
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ./OpenWRT-Action/artifact/*      
