name: Reuse_Action_LeanWRT-EA8500

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:   

    - name: Initialization
      uses: thinkcyy/Action_Initialization@main            
    
    - name: Compile
      uses: thinkcyy/Action_LeanWRT_composite@main
      with:
           ROUTER_MODEL: EA8500
           #COMPILE_CONFIG: EA8500-20240424-remove-igmpproxy   
           OP_REPO: coolsnowwolf/lede
           #REPO_DEPTH: 1
           #切换至2024.3.31版本
           REPO_COMMIT: 917b7878879dd3681c138ed5bea03f50ecda454d
           
    - name: Create release
      id: create_release
      uses: ncipollo/release-action@v1.12.0
      with:
        name: OpenWrt-${{ env.TAG_NAME }}
        allowUpdates: true
        tag: ${{ env.TAG_NAME }}
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ./OpenWRT-Action/artifact/*      
