name: Reuse_Action_zhKong-AX6

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Show system
      run: |
        echo -e "Total CPU cores\t: $(nproc)"
        cat /proc/cpuinfo | grep 'model name'
        ulimit -a
        echo "ROUTER_MODEL=AX6" >> $GITHUB_ENV
        echo "FILES_CONFIG=public" >> $GITHUB_ENV
        echo "COMPILE_CONFIG=AX6-20240325-avahi" >> $GITHUB_ENV    

    - name: Prepare Firmware Repo
      uses: thinkcyy/Action_zhKong_1-checkout-and-config@main
      with:
           ROUTER_MODEL: AX6
           COMPILE_CONFIG: AX6-20240325-avahi 
           
    - name: Compile
      uses: thinkcyy/Action_zhKong_2-compile@main
      with:
           ROUTER_MODEL: AX6
           COMPILE_CONFIG: AX6-20240325-avahi 
           
    - name: generate tag
      run: |        
        tag_name=$(date +%Y%m%d-%H%M)
        echo "tag_name=${tag_name}" >>$GITHUB_ENV
        
    - name: Organize files
      id: organize
      run: |
        rm -rf ./artifact/
        mkdir -p ./artifact/
        cp -rf $(find ./openwrt/bin/targets/ -type f -name "*sysupgrade*") ./artifact/
        cp -rf $(find ./openwrt/bin/targets/ -type f -name "*.buildinfo") ./artifact/
        cp ./openwrt/.config ./artifact/defconfig-${{ inputs.COMPILE_CONFIG }}.config
        cd ./artifact/
        rename 's/sysupgrade.bin/sysupgrade-${{ inputs.COMPILE_CONFIG }}_${{ env.tag_name }}.bin/' *

        
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: OpenWrt-${{ inputs.COMPILE_CONFIG }}-${{ env.tag_name }}
        path: ./artifact/
