name: test

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: touch
      run: |
        mkdir -p runner_root/openwrt/bin/targets/
        touch runner_root/openwrt/bin/targets/sysupgrade.bin
        echo "TAG_NAME=test-tag-name" >> $GITHUB_ENV
        echo "TYPE_NAME=[OpenWrt]" >> $GITHUB_ENV

    - name: Upload
      uses: thinkcyy/Action_OpenWrt_composite@release
      
    - name: Create release
      uses: ncipollo/release-action@main
      with:
        name: ++Archive++-${{ env.TAG_NAME }}
        allowUpdates: true
        tag: ${{ env.TAG_NAME }}
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ./runner_root/artifact/*
