name: test

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Prepare
      uses: thinkcyy/Action_OpenWrt_composite@prepare_test
      with:
           ROUTER_MODEL: AX6
           COMPILE_CONFIG_BASE: AgustinLorenzo.default
           COMPILE_CONFIG_DIFF: AgustinLorenzo.diff.20240709-zerotier
           #COMPILE_CONFIG: AX6-main-nss-20240731-all-ipk-remove-i18n-es
           IMAGEBUILDER: y
           REPO_TYPE: zhKong
           OP_REPO: AgustinLorenzo/openwrt
           REPO_BRANCH: main_nss
           #REPO_BRANCH: ipq807x-nsswifi-2024-07-31-0100
           #REPO_DATE: '2024-07-05T23:59:59+08:00'
           #REPO_DATE: 794264e
           #DEFAULT_FEEDS: feeds.conf.default-main_nss_wifi
           #EXTRA_FEEDS: add_feeds_cus_lean_luci
           CUSTOM_FEEDS_SH: custom_feeds-AgustinLorenzo
           #如果DEFAULT_FEEDS已自带HASH，MATCH_FEED_HASH要取消设定
           #MATCH_FEED_HASH: y
           #ACTION_DATE: fc19ca2
           #ACTION_DATE: '2024-07-31T23:59:59+08:00'
           #FEEDS_DATE:  '2024-07-24T23:59:59+08:00'

    - name: touch
      run: |
        [[ ! -d "./runner_root/openwrt/bin/targets" ]] && mkdir -p ./runner_root/openwrt/bin/targets/
        touch ./runner_root/openwrt/bin/targets/test.sysupgrade.bin
        touch ./runner_root/openwrt/bin/targets/test.imagebuilder.zst
        #echo "TAG_NAME=test-tag-name" >> $GITHUB_ENV
        echo "TYPE_NAME=[OpenWrt]" >> $GITHUB_ENV

    - name: Upload
      uses: thinkcyy/Action_OpenWrt_composite@release
      
#    - name: Create release
 #     uses: ncipollo/release-action@main
  #    with:
   #     name: ${{ env.TYPE_NAME }}-${{ env.TAG_NAME }}
    #    allowUpdates: true
     #   tag: tag-${{ env.TAG_NAME }}
      #  replacesArtifacts: true
       # token: ${{ secrets.GITHUB_TOKEN }}
        #artifacts: ./runner_root/artifact/*
