name: zhKong_main_nss-AX6-archive

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        
    - name: Initialization
      uses: thinkcyy/Action_Initialization@quick                
                   
    - name: Prepare
      uses: thinkcyy/Action_OpenWrt_composite@prepare_v5
      with:
           ROUTER_MODEL: AX6
           COMPILE_CONFIG_BASE: AgustinLorenzo.default.20240801-nss-fw-12.5
           COMPILE_CONFIG_DIFF: common.cust.package.diff
           COMPILE_CONFIG: AgustinLorenzo.nss.fw.12.5.diff.all.ipk-test
           IMAGEBUILDER: y
           REPO_TYPE: zhKong
           OP_REPO: AgustinLorenzo/openwrt
           #REPO_BRANCH: main_nss
           REPO_BRANCH: ipq807x-nsswifi-2024-07-31-0100
           #REPO_DATE: '2024-07-25T23:59:59+08:00'
           #REPO_DATE: 88384cc
           #DEFAULT_FEEDS: feeds.conf.default-main_nss_wifi
           #EXTRA_FEEDS: add_feeds_cus_lean_luci
           CUSTOM_FEEDS_SH: custom_feeds-AgustinLorenzo
           #如果DEFAULT_FEEDS已自带HASH，MATCH_FEED_HASH要取消设定
           #MATCH_FEED_HASH: y
           #ACTION_DATE: fc19ca2
           #ACTION_DATE: '2024-08-02T23:59:59+08:00'
           FEEDS_DATE:  '2024-07-31T23:59:59+08:00'
           
    - name: Download package sources
      working-directory: ${{ github.workspace }}/runner_root/openwrt
      run: make download V=s

    - name: Build tools
      working-directory: ${{ github.workspace }}/runner_root/openwrt
      run: |
        make tools/install -j$(nproc) V=s || \
        make tools/install V=s
        
    - name: Build toolchain
      working-directory: ${{ github.workspace }}/runner_root/openwrt
      run: |
        make toolchain/install -j$(nproc) V=s || \
        make toolchain/install V=s

    - name: Build target images
      working-directory: ${{ github.workspace }}/runner_root/openwrt
      run: |
        make -j$(nproc) V=s || \
        make V=s
        
        echo "RELEASE_NAME_PREFIX=[Archive]" >> $GITHUB_ENV

    - name: Upload
      uses: thinkcyy/Action_OpenWrt_composite@release
      
    - name: Create release
      uses: ncipollo/release-action@main
      with:
        name: ${{ env.RELEASE_NAME_PREFIX }}-OpenWrt-${{ env.REPO_TYPE }}-${{ env.TAG_NAME }}
        allowUpdates: true
        tag: ${{ env.TAG_NAME }}
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ./runner_root/artifact/*
